# Site
name: "Patrick German - Freelance Motion Designer & Animator"
title: "Patrick German - Freelance Motion Designer & Animator"
description: "Patrick German is a Freelance Motion Graphics Designer and Animator based in Bonn, Germany. Come and say hello!"
logo: 'assets/images/PG-logo2.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
include: ["_pages"]
permalink: /:title/
email: mrpatrickgerman@gmail.com
instagram: "https://instagram.com/patrick_german_"

# Collections
collections:
  projects:
    output: true

# Authors
authors:
  patrick:
    name: Patrick
    display_name: Patrick
    email: mrpatrickgerman@gmail.com
    web: https://www.patrickgerman.com
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
